/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/daily` | `/daily`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notes` | `/notes`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/[book]/[chapter]` | `/[book]/[chapter]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/chapters/[book]` | `/chapters/[book]`, params: Router.UnknownInputParams & { book: string | number; } } | { pathname: `/reader/[book]/[chapter]`, params: Router.UnknownInputParams & { book: string | number;chapter: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(tabs)'}/daily` | `/daily`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notes` | `/notes`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/[book]/[chapter]` | `/[book]/[chapter]`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(tabs)'}/chapters/[book]` | `/chapters/[book]`, params: Router.UnknownOutputParams & { book: string; } } | { pathname: `/reader/[book]/[chapter]`, params: Router.UnknownOutputParams & { book: string;chapter: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(tabs)'}/daily${`?${string}` | `#${string}` | ''}` | `/daily${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notes${`?${string}` | `#${string}` | ''}` | `/notes${`?${string}` | `#${string}` | ''}` | `/../constants/styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/[book]/[chapter]${`?${string}` | `#${string}` | ''}` | `/[book]/[chapter]${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/daily` | `/daily`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notes` | `/notes`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/[book]/[chapter]` | `/[book]/[chapter]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | `${'/(tabs)'}/chapters/${Router.SingleRoutePart<T>}` | `/chapters/${Router.SingleRoutePart<T>}` | `/reader/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/chapters/[book]` | `/chapters/[book]`, params: Router.UnknownInputParams & { book: string | number; } } | { pathname: `/reader/[book]/[chapter]`, params: Router.UnknownInputParams & { book: string | number;chapter: string | number; } };
    }
  }
}
